version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shared_models_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  service-a:
    build:
      context: .
      dockerfile: packages/service-a/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=shared_models_db
      - PORT=3001
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  service-b:
    build:
      context: .
      dockerfile: packages/service-b/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=shared_models_db
      - PORT=3002
      - SERVICE_A_URL=http://service-a:3001
    depends_on:
      mysql:
        condition: service_healthy
      service-a:
        condition: service_started
    restart: unless-stopped

volumes:
  mysql_data: